const usersData = [
  { id: 0, username: "administrator",PostStatus:"Removed", postImage: 'https://dashchallengesapi.com/static/media/2020-5-3-3-15-55-challengeImage.PNG', commit: "This is commit", DataFlagged: '2020/6/6', DataPosted: '2020/6/6', ofFlages: "430 Flages", userStatus: "No Warning", challengeTitle: 'Strength Training1', description: 'Strength Training1-description', plan: 'Dash', startDate: 'June 6,2020', version: '1.0', host: "Dash", signUps: "343", leftChallenge: "-22", challengeView: "78643", activeDate: "Starts in 3:22:22:20", featured: "yes", status: 'current' },
  { id: 1, username: "administrator", PostStatus:"UnFlagged",postImage: '', commit: "This is commit", DataFlagged: '2020/6/6', DataPosted: '2020/6/6', ofFlages: "430 Flages", userStatus: "warned", challengeTitle: 'Strength Training2', description: 'Strength Training2-description', plan: 'Dash', startDate: 'June 6,2020', version: '1.0', host: "Dash", signUps: "343", leftChallenge: "-22", challengeView: "78643", activeDate: "Starts in 3:22:22:20", featured: "yes", status: 'current' },
  { id: 2, username: "user2", PostStatus:"Removed",postImage: '', commit: "This is commit", DataFlagged: '2020/6/6', DataPosted: '2020/6/6', ofFlages: "430 Flages", userStatus: "No Warning", challengeTitle: 'Strength Training3', description: 'Strength Training3-description', plan: 'Dash', startDate: 'June 6,2020', version: '2.0', host: "Dash", signUps: "343", leftChallenge: "-22", challengeView: "78643", activeDate: "Starts in 3:22:22:20", featured: "yes", status: 'past' },
  { id: 3, username: "user3", PostStatus:"Removed",postImage: '', commit: "This is commit", DataFlagged: '2020/6/6', DataPosted: '2020/6/6', ofFlages: "430 Flages", userStatus: "warned", challengeTitle: 'Strength Training4', description: 'Strength Training4-description', plan: 'Dash', startDate: 'June 6,2020', version: '3.0', host: "Dash", signUps: "343", leftChallenge: "-22", challengeView: "78643", activeDate: "Starts in 3:22:22:20", featured: "yes", status: 'current' },
  { id: 4, username: "user4", PostStatus:"Removed",postImage: 'https://dashchallengesapi.com/static/media/2020-5-3-3-15-55-challengeImage.PNG', commit: "This is commit", DataFlagged: '2020/6/6', DataPosted: '2020/6/6', ofFlages: "430 Flages", userStatus: "No Warning", challengeTitle: 'Strength Training5', description: 'Strength Training5-description', plan: 'Dash', startDate: 'June 6,2020', version: '4.0', host: "Dash", signUps: "343", leftChallenge: "-22", challengeView: "78643", activeDate: "Starts in 3:22:22:20", featured: "yes", status: 'remove' },
  { id: 5, username: "user5", PostStatus:"Removed",postImage: 'https://dashchallengesapi.com/static/media/2020-5-3-3-15-55-challengeImage.PNG', commit: "This is commit", DataFlagged: '2020/6/6', DataPosted: '2020/6/6', ofFlages: "430 Flages", userStatus: "warned", challengeTitle: 'Strength Training6', description: 'Strength Training6-description', plan: 'Dash', startDate: 'June 6,2020', version: '2.0', host: "Dash", signUps: "343", leftChallenge: "-22", challengeView: "78643", activeDate: "Starts in 3:22:22:20", featured: "yes", status: 'current' },
]

export default usersData
