const usersData = [
  { id: 0, label: 'Strength Training1', video: 'https://dashchallengesapi.com/static/media/2020-5-3-3-15-55-challengeImage.PNG', CardTitle: 'Home Exercise 1', cards: "345", description: 'Strength Training1-description', Name: 'Strength Training', CardType: 'video Card', EasyVariation: 'Decline Knee Core Tucks', HardVariation: "InCline Knee Core Tucks", Audio: "yes", leftChallenge: "-22", challengeView: "78643", activeDate: "Starts in 3:22:22:20", featured: "yes", status: 'current' },
  { id: 1, label: 'Strength Training2', video: 'https://dashchallengesapi.com/static/media/2020-5-3-3-15-55-challengeImage.PNG', CardTitle: 'Home Exercise 2', cards: "345", description: 'Strength Training2-description', Name: 'HIIT for Fast-Loss',  CardType: 'Exercise Card', EasyVariation: 'Decline Knee Core Tucks', HardVariation: "InCline Knee Core Tucks", Audio: "yes", leftChallenge: "-22", challengeView: "78643", activeDate: "Starts in 3:22:22:20", featured: "yes", status: 'current' },
  { id: 2, label: 'Strength Training3', video: 'https://dashchallengesapi.com/static/media/2020-5-3-3-15-55-challengeImage.PNG', CardTitle: 'Home Exercise 3', cards: "345", description: 'Strength Training3-description', Name: 'Booty Builder',  CardType: 'video Card', EasyVariation: 'Decline Knee Core Tucks', HardVariation: "InCline Knee Core Tucks", Audio: "yes", leftChallenge: "-22", challengeView: "78643", activeDate: "Starts in 3:22:22:20", featured: "yes", status: 'past' },
  { id: 3, label: 'Strength Training4', video: 'https://dashchallengesapi.com/static/media/2020-5-3-3-15-55-challengeImage.PNG', CardTitle: 'Home Exercise 4', cards: "345", description: 'Strength Training4-description', Name: 'Abs & Core',  CardType: 'video Card',EasyVariation: 'Decline Knee Core Tucks', HardVariation: "InCline Knee Core Tucks", Audio: "yes", leftChallenge: "-22", challengeView: "78643", activeDate: "Starts in 3:22:22:20", featured: "yes", status: 'current' },
  { id: 4, label: 'Strength Training5', video: 'https://dashchallengesapi.com/static/media/2020-5-3-3-15-55-challengeImage.PNG', CardTitle: 'Home Exercise 5', cards: "345", description: 'Strength Training5-description', Name: 'Body',  CardType: 'video Card', EasyVariation: 'Decline Knee Core Tucks', HardVariation: "InCline Knee Core Tucks", Audio: "yes", leftChallenge: "-22", challengeView: "78643", activeDate: "Starts in 3:22:22:20", featured: "yes", status: 'remove' },
  { id: 5, label: 'Strength Training6', video: 'https://dashchallengesapi.com/static/media/2020-5-3-3-15-55-challengeImage.PNG', CardTitle: 'Home Exercise 6', cards: "345", description: 'Strength Training6-description', Name: 'Yoga & Stretching',  CardType: 'video Card', EasyVariation: 'Decline Knee Core Tucks', HardVariation: "InCline Knee Core Tucks", Audio: "yes", leftChallenge: "-22", challengeView: "78643", activeDate: "Starts in 3:22:22:20", featured: "yes", status: 'current' },
]

export default usersData
